### ISSUE TITLE
train takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wing158** [Chaphlagical/Deblur-GS#1]
~/Deblur-GS# python train.py -s exblur_release/bench --eva
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from utils.vis_utils import vis_cameras
  File "/root/Deblur-GS/utils/vis_utils.py", line 2, in <module>
    from scene.cameras import cam2world
  File "/root/Deblur-GS/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/root/Deblur-GS/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/root/Deblur-GS/scene/gaussian_model.py", line 14, in <module>
    from utils.general_utils import inverse_sigmoid, get_expon_lr_func, build_rotation
  File "/root/Deblur-GS/utils/general_utils.py", line 135, in <module>
    def visualize_depth(depth, minmax=None, cmap=cv2.COLORMAP_TURBO):
TypeError: __init__() takes 1 positional argument but 2 were given

请问命令参数错了，还是opencv-python版本有问题？

**Comment by Chaphlagical** [comment]
> ~/Deblur-GS# python train.py -s exblur_release/bench --eva Traceback (most recent call last): File "train.py", line 16, in from utils.vis_utils import vis_cameras File "/root/Deblur-GS/utils/vis_utils.py", line 2, in from scene.cameras import cam2world File "/root/Deblur-GS/scene/**init**.py", line 16, in from scene.dataset_readers import sceneLoadTypeCallbacks File "/root/Deblur-GS/scene/dataset_readers.py", line 24, in from scene.gaussian_model import BasicPointCloud File "/root/Deblur-GS/scene/gaussian_model.py", line 14, in from utils.general_utils import inverse_sigmoid, get_expon_lr_func, build_rotation File "/root/Deblur-GS/utils/general_utils.py", line 135, in def visualize_depth(depth, minmax=None, cmap=cv2.COLORMAP_TURBO): TypeError: **init**() takes 1 positional argument but 2 were given
> 
> 请问命令参数错了，还是opencv-python版本有问题？

是不是应该--eval而不是eva

**Comment by wing158** [comment]
目录前目录结构是： 
root@d3d0bbce3ea9:~/gs2/Deblur-GS-main/synthetic_release/blurwine/images# ls
000.png  002.png  004.png  006.png  008.png  010.png  012.png  014.png  016.png  018.png  020.png  022.png  024.png  026.png  028.png  030.png  032.png
001.png  003.png  005.png  007.png  009.png  011.png  013.png  015.png  017.png  019.png  021.png  023.png  025.png  027.png  029.png  031.png  033.png
root@d3d0bbce3ea9:~/gs2/Deblur-GS-main/synthetic_release/blurwine/images# cd ../../../
root@d3d0bbce3ea9:~/gs2/Deblur-GS-main# python train.py -s synthetic_release/blurwine/ --eval
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from utils.vis_utils import vis_cameras
  File "/root/gs2/Deblur-GS-main/utils/vis_utils.py", line 2, in <module>
    from scene.cameras import cam2world
  File "/root/gs2/Deblur-GS-main/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/root/gs2/Deblur-GS-main/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/root/gs2/Deblur-GS-main/scene/gaussian_model.py", line 14, in <module>
    from utils.general_utils import inverse_sigmoid, get_expon_lr_func, build_rotation
  File "/root/gs2/Deblur-GS-main/utils/general_utils.py", line 135, in <module>
    def visualize_depth(depth, minmax=None, cmap=cv2.COLORMAP_TURBO):
TypeError: __init__() takes 1 positional argument but 2 were given


环境变量：
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.__version__)
4.9.0
>>> import torch;
>>> print(torch.__version__);
1.12.1+cu116
>>> print(torch.cuda.is_available())
True

执行了 python train.py -s synthetic_release/blurwine/ --eval 仍是报同样的错误

**Comment by Chaphlagical** [comment]
是torch no_grad的问题，修了一下

**Comment by wing158** [comment]
python train.py -s synthetic_release/blurwine/ --eval
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from utils.vis_utils import vis_cameras
  File "/root/gs3/Deblur-GS/utils/vis_utils.py", line 2, in <module>
    from scene.cameras import cam2world
  File "/root/gs3/Deblur-GS/scene/__init__.py", line 19, in <module>
    from utils.camera_utils import cameraList_from_camInfos, camera_to_JSON
  File "/root/gs3/Deblur-GS/utils/camera_utils.py", line 12, in <module>
    from scene.cameras import Camera
  File "/root/gs3/Deblur-GS/scene/cameras.py", line 21, in <module>
    class Camera(nn.Module):
  File "/root/gs3/Deblur-GS/scene/cameras.py", line 177, in Camera
    def get_test_pose(self):
TypeError: __init__() takes 1 positional argument but 2 were given

更新后已有改善，引有from utils.vis_utils import vis_cameras 到cameras.py的报错，还需要完善下

**Comment by Chaphlagical** [comment]
之前数据集有问题，可以下载readme更新的数据集再试试

**Comment by kappo96** [comment]
我新下载了synthetic_release，还是这个问题
![image](https://github.com/Chaphlagical/Deblur-GS/assets/61680101/ccf8c04d-4c9c-42ed-8ee7-5134a015ea77)

**Comment by Chaphlagical** [comment]
好像是没更新上，现在再试试

**Comment by giich** [comment]
> 我新下载了synthetic_release，还是这个问题 ![image](https://private-user-images.githubusercontent.com/61680101/330308100-ccf8c04d-4c9c-42ed-8ee7-5134a015ea77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzQyNDgsIm5iZiI6MTcxNTY3Mzk0OCwicGF0aCI6Ii82MTY4MDEwMS8zMzAzMDgxMDAtY2NmOGMwNGQtNGM5Yy00MmVkLThlZTctNTEzNGEwMTVlYTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDkzNTY1NmM3YjU4MTNiYmJmMzY4ODY4NDYxMjVlMTFkNTM5MzJiNTNiNmFlNWQxYTk0ODAxYmI4M2FhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6qwreXygexdvH2QrRt_ahV7d5Y3gwOEl1rRf5pjYHi0)

It is kinda looking for sparse folder but it is not there i guess

**Comment by wing158** [comment]
解决方法：
1：重新下载整个project的代码，安装依赖及submodule下三个子项目重新安装
2：安装pip install visdom后
     python -m visdom.server -port 2333
3：cameras.py需要将@torch no_grad备注起来 @Chaphlagical  请作者修正下。
4：重新下载exblur_release或synthetic_release数据。
5：目前training正常运行中
