### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

### ISSUE THREAD

**Issue by kgkgkgjb** [Chaphlagical/Deblur-GS#16]
Hi, thank you very much for your contribution!

Loading Training Cameras [23/09 16:49:55]
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 66, in training
    scene = Scene(dataset, gaussians)
  File "/workspace/Deblur-GS/scene/__init__.py", line 95, in __init__
    midas, scene_info.train_cameras, resolution_scale, args)
  File "/workspace/Deblur-GS/utils/camera_utils.py", line 69, in cameraList_from_camInfos
    camera_list.append(loadCam(midas, args, id, c, resolution_scale))
  File "/workspace/Deblur-GS/utils/camera_utils.py", line 62, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device, control_pts_num=control_pts_num, mode=args.mode)
  File "/workspace/Deblur-GS/scene/cameras.py", line 48, in __init__
    self.predict_depth = estimate_depth(midas, self.original_image)
  File "/workspace/Deblur-GS/utils/depth_utils.py", line 15, in estimate_depth
    prediction = midas(norm_img)
  File "/opt/conda/envs/deblur_gs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/torch/hub/intel-isl_MiDaS_master/midas/dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "/root/.cache/torch/hub/intel-isl_MiDaS_master/midas/dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "/root/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/vit.py", line 13, in forward_vit
    return forward_adapted_unflatten(pretrained, x, "forward_flex")
  File "/root/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "<string>", line 1, in <module>
  File "/root/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/vit.py", line 68, in forward_flex
    x = blk(x)
  File "/opt/conda/envs/deblur_gs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/deblur_gs/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 164, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/opt/conda/envs/deblur_gs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/deblur_gs/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 97, in forward
    attn = q @ k.transpose(-2, -1)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

**Comment by teacherlcy** [comment]
Have you solved this problem? Im facing the same problem
